import React, { useEffect, useRef } from 'react';
import  BlurBackground  from "../components/BlurBackground";


const LedPaintings = () => {
  const containerSliders = useRef(null);


  useEffect(() => {
    if (containerSliders.current) {
      [...containerSliders.current.querySelectorAll('.slider')].forEach(
        el => (el.scrollLeft = containerSliders.current.scrollWidth / 2.5)
      );
    }
  }, [containerSliders]);

  return (
    <section className='page2-led-paintings'>
      <div ref={containerSliders} className='container-sliders'>
        <aside className='slider'>
          <img
            src='assets/led-paintings/img-1.webp'
            alt='image 1'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-2.webp'
            alt='image 2'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-3.webp'
            alt='image 3'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-4.webp'
            alt='image 4'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-5.webp'
            alt='image 5'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-6.webp'
            alt='image 6'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-7.webp'
            alt='image 7'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-8.webp'
            alt='image 8'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-9.webp'
            alt='image 9'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-10.webp'
            alt='image 10'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-11.webp'
            alt='image 11'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-12.webp'
            alt='image 12'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-13.webp'
            alt='image 13'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-14.webp'
            alt='image 14'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-15.webp'
            alt='image 15'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-16.webp'
            alt='image 16'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-17.webp'
            alt='image 17'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-18.webp'
            alt='image 18'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-19.webp'
            alt='image 19'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-20.webp'
            alt='image 20'
            loading='lazy'
          />
        </aside>
        <aside className='slider'>
          <img
            src='assets/led-paintings/img-21.webp'
            alt='21'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-22.webp'
            alt='22'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-23.webp'
            alt='23'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-24.webp'
            alt='24'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-25.webp'
            alt='25'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-26.webp'
            alt='26'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-27.webp'
            alt='27'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-28.webp'
            alt='28'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-29.webp'
            alt='29'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-30.webp'
            alt='30'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-31.webp'
            alt='31'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-32.webp'
            alt='32'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-33.webp'
            alt='33'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-34.webp'
            alt='34'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-35.webp'
            alt='35'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-36.webp'
            alt='36'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-37.webp'
            alt='37'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-38.webp'
            alt='38'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-39.webp'
            alt='39'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-40.webp'
            alt='40'
            loading='lazy'
          />
        </aside>
        <aside className='slider'>
          <img
            src='assets/led-paintings/img-41.webp'
            alt='41'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-42.webp'
            alt='42'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-43.webp'
            alt='43'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-44.webp'
            alt='44'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-45.webp'
            alt='45'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-46.webp'
            alt='46'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-47.webp'
            alt='47'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-48.webp'
            alt='48'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-49.webp'
            alt='49'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-50.webp'
            alt='50'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-51.webp'
            alt='51'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-52.webp'
            alt='52'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-53.webp'
            alt='53'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-54.webp'
            alt='54'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-55.webp'
            alt='55'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-56.webp'
            alt='56'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-57.webp'
            alt='57'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-58.webp'
            alt='58'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-59.webp'
            alt='59'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-60.webp'
            alt='60'
            loading='lazy'
          />
        </aside>
        <aside className='slider'>
          <img
            src='assets/led-paintings/img-61.webp'
            alt='61'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-62.webp'
            alt='62'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-63.webp'
            alt='63'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-64.webp'
            alt='64'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-65.webp'
            alt='65'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-66.webp'
            alt='66'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-67.webp'
            alt='67'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-68.webp'
            alt='68'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-69.webp'
            alt='69'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-70.webp'
            alt='70'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-71.webp'
            alt='71'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-72.webp'
            alt='72'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-73.webp'
            alt='73'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-74.webp'
            alt='74'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-75.webp'
            alt='75'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-76.webp'
            alt='76'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-77.webp'
            alt='77'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-78.webp'
            alt='78'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-79.webp'
            alt='79'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-80.webp'
            alt='80'
            loading='lazy'
          />
        </aside>
        <aside className='slider'>
          *{' '}
          <img
            src='assets/led-paintings/img-81.webp'
            alt='81'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-82.webp'
            alt='82'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-83.webp'
            alt='83'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-84.webp'
            alt='84'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-85.webp'
            alt='85'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-86.webp'
            alt='86'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-87.webp'
            alt='87'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-88.webp'
            alt='88'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-89.webp'
            alt='89'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-90.webp'
            alt='90'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-91.webp'
            alt='91'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-92.webp'
            alt='92'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-93.webp'
            alt='93'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-94.webp'
            alt='94'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-95.webp'
            alt='95'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-96.webp'
            alt='96'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-97.webp'
            alt='97'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-98.webp'
            alt='98'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-99.webp'
            alt='99'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-100.webp'
            alt='100'
            loading='lazy'
          />
        </aside>
        <aside className='slider'>
          <img
            src='assets/led-paintings/img-101.webp'
            alt='101'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-102.webp'
            alt='102'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-103.webp'
            alt='103'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-104.webp'
            alt='104'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-105.webp'
            alt='105'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-106.webp'
            alt='106'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-107.webp'
            alt='107'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-108.webp'
            alt='108'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-109.webp'
            alt='109'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-110.webp'
            alt='110'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-111.webp'
            alt='111'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-112.webp'
            alt='112'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-113.webp'
            alt='113'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-114.webp'
            alt='114'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-115.webp'
            alt='115'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-116.webp'
            alt='116'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-117.webp'
            alt='117'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-118.webp'
            alt='118'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-119.webp'
            alt='119'
            loading='lazy'
          />
          <img
            src='assets/led-paintings/img-120.webp'
            alt='120'
            loading='lazy'
          />
        </aside>

        <BlurBackground color1="#e81cff" color2="#00ff87" color3="#f8acff" />
      </div>

    </section>
  );
};

export default LedPaintings;
